version: "3.8"

services:
  webserver:
    build:
      context: ./bin/${PHPVERSION}
    container_name: "${COMPOSE_PROJECT_NAME}-${PHPVERSION}"
    restart: "always"
    read_only: false
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:${CONTAINER_HTTP_PORT}"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:${CONTAINER_HTTPS_PORT}"
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${SSL_DIR-./config/ssl}:/etc/apache2/ssl/
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
      - ${XDEBUG_LOG_DIR-./logs/xdebug}:/var/log/xdebug
      # - ${PROJECTS_DIRECTORY-./projects}:/var/www/html/projects
      # DIRECTORY IS MOUNTED AS rw BY DEFAULT (rw - ro)
      # w-if-proper-permissions-are-set
      # - ${WWW2-./www2}:/var
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/html}
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      HOST_MACHINE_MYSQL_PORT: ${HOST_MACHINE_MYSQL_PORT}
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=${XDEBUG_PORT}"
      WORDPRESS_HOST_PORT: ${HOST_MACHINE_WP_PORT}
      WORDPRESS_DB_HOST: ${WP_DB_HOST}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # links:
    #   - database
  database:
    build:
      context: "./bin/${DATABASE}"
    container_name: "${COMPOSE_PROJECT_NAME}-${DATABASE}"
    hostname: "${COMPOSE_PROJECT_NAME}-${DATABASE}"
    restart: "always"
    ports:
      - "${HOST_MACHINE_IP}:${HOST_MACHINE_MYSQL_PORT}:${CONTAINER_MYSQL_PORT}"
    volumes:
      - ${MYSQL_INITDB_DIR-./config/initdb}:/docker-entrypoint-initdb.d
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin
    container_name: "${COMPOSE_PROJECT_NAME}-phpmyadmin"
    restart: "always"
    environment:
      PMA_HOST: database
      PMA_PORT: ${CONTAINER_MYSQL_PORT}
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    ports:
      - "${HOST_MACHINE_PMA_PORT}:${CONTAINER_HTTP_PORT}"
      - "${HOST_MACHINE_PMA_SECURE_PORT}:${CONTAINER_HTTPS_PORT}"
    volumes:
      - /sessions
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    # links:
    #   - database
  redis:
    container_name: "${COMPOSE_PROJECT_NAME}-redis"
    restart: "always"
    image: redis:latest
    ports:
      - "${HOST_MACHINE_IP}:${HOST_MACHINE_REDIS_PORT}:${CONTAINER_REDIS_PORT}"
  wordpress:
    container_name: "${COMPOSE_PROJECT_NAME}-wordpress"
    restart: "always"
    image: wordpress:latest
    ports:
      - "${HOST_MACHINE_IP}:${HOST_MACHINE_WP_PORT}:${CONTAINER_HTTP_PORT}"
    environment:
      WORDPRESS_DB_HOST: ${WP_DB_HOST}:${HOST_MACHINE_MYSQL_PORT}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX}
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - database
    volumes:
      - ./wp-app:/var/www/html:rw
      # - ./wp-data/wp-content:/var/www/html/wp-content:rw
      # - ./wp-data/wp-content:/var/www/html/wp-content:rw
      # - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      # - ./wp-data/wp-config:/var/www/html/wp-config.php
    # links:
    #   - database
